#include "Pstd/pstd_compilercmd.h"
#include "Pstd/pstd_int.h"
#include "Pstd/pstd_io.h"
#include "Pstd/pstd_port.h"
#include "Pstd/pstd_string.h"
#include "Pstd/pstd_kernel.h"
#include "Pstd/pstd_kernel.h"
#include "Pstd/pstd_diskdriver.h"

#include "FatFs/ff.c"
#include "FatFs/ffunicode.c"
#include "FatFs/diskio.c"

#include "Pstd/pstd_fs.h"
#include "Pstd/pstd_klog.h"
#include "Pstd/pstd_kmalloc.h"

#include "Pstd/pstd_e820.h"
#include "Pstd/pstd_pmm.h"
#include "Pstd/pstd_paging.h"
#include "Pstd/pstd_gdt.h"
#include "Pstd/pstd_idt.h"
#include "Pstd/pstd_exc.h"
#include "Pstd/pstd_dwn.h"
#include "Pstd/pstd_proc.h"
#include "Pstd/pstd_syscall.h"
#include "Pstd/pstd_init.h"

#include "Pstd/pstd_kapi.h"
